using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApplication1.Migrations
{
    /// <inheritdoc />
    public partial class AddPartnersTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS partners (
                    partner_id   integer GENERATED BY DEFAULT AS IDENTITY,
                    partner_name text,
                    partner_type text,
                    role_type    text,
                    contact_name text,
                    email        text,
                    phone        text,
                    region       text,
                    status       text,
                    start_date   date,
                    end_date     date,
                    notes        text,
                    CONSTRAINT ""PK_partners"" PRIMARY KEY (partner_id)
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "partners");
        }
    }
}
