using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApplication1.Migrations
{
    /// <inheritdoc />
    public partial class AddAdmissionChecklists : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Table was already created in the first partial run.
            // Use IF NOT EXISTS so re-running is safe.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS admission_checklists (
                    checklist_id integer GENERATED BY DEFAULT AS IDENTITY,
                    resident_id integer NOT NULL,
                    resident_code text,
                    social_worker_email text,
                    resident_in_facility boolean NOT NULL,
                    checked_items text NOT NULL,
                    status text NOT NULL,
                    submitted_at timestamp with time zone NOT NULL,
                    reviewed_at timestamp with time zone,
                    reviewed_by text,
                    admin_notes text,
                    CONSTRAINT ""PK_admission_checklists"" PRIMARY KEY (checklist_id)
                );

                CREATE INDEX IF NOT EXISTS ix_admission_checklists_resident_id
                    ON admission_checklists (resident_id);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "admission_checklists");
        }
    }
}
