-- ============================================================
-- Manual migration for Supabase: AddSocialWorkersTable
-- Run this in the Supabase SQL Editor
-- ============================================================

-- 1. Create the migrations history table if it doesn't exist
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- 2. Record the first migration (Identity) so EF knows it's applied
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260406220902_AddIdentity', '10.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

-- 3. Create the social_workers table
CREATE TABLE IF NOT EXISTS social_workers (
    social_worker_id integer GENERATED BY DEFAULT AS IDENTITY,
    full_name text NOT NULL,
    first_name text,
    last_name text,
    email text,
    phone text,
    safehouse_id integer,
    status text NOT NULL DEFAULT 'Active',
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_social_workers" PRIMARY KEY (social_worker_id)
);

-- 4. Add social_worker_id column to existing tables (safe if already exists)
ALTER TABLE process_recordings
    ADD COLUMN IF NOT EXISTS social_worker_id integer;

ALTER TABLE home_visitations
    ADD COLUMN IF NOT EXISTS social_worker_id integer;

-- 5. Create indexes on the new FK columns
CREATE INDEX IF NOT EXISTS "IX_process_recordings_social_worker_id"
    ON process_recordings (social_worker_id);

CREATE INDEX IF NOT EXISTS "IX_home_visitations_social_worker_id"
    ON home_visitations (social_worker_id);

CREATE INDEX IF NOT EXISTS "IX_social_workers_safehouse_id"
    ON social_workers (safehouse_id);

-- 6. Record this migration as applied
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260407171834_AddSocialWorkersTable', '10.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;
